name: xarrayutils-docs
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
  # Packages which are needed to execute your examples
  # These will vary
  - ipython
  - matplotlib
  - xarray
  - netcdf4
  - dask
  - numpy
  - xarray
  - scipy
  - nc-time-axis
  - astropy
  - intake-esm
  - gcsfs
  - nbsphinx
  - jupyter_client
  - sphinxcontrib-srclinks
  - pandoc
  - recommonmark
  - pip
  - pip:
     - sphinx_pangeo_theme
