name: xarrayutils-docs
dependencies:
  - python=3.8
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
  # Packages which are needed to execute your examples
  # These will vary
  - ipython
  - matplotlib
  - xarray
  - netcdf4
  - dask
  - numpy
  - xarray
  - pip
  - pip:
    - scipy
    - nc-time-axis
    - astropy
    - intake-esm
    - gcsfs
    - nbsphinx
    - jupyter_client
    - sphinx_pangeo_theme
    - sphinxcontrib-srclinks
    - pandoc
    - recommonmark
