name: xarrayutils-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - scipy
  - numpy
  - xarray
  - numpydoc
  - pandoc
  - recommonmark
  - sphinx
  - sphinx_rtd_theme
  - ipykernel
  # Packages which are needed to execute your examples
  # These will vary
  - ipython
  - matplotlib
  - xarray
  - netcdf4
  - dask
  - numpy
  - nc-time-axis
  - astropy
  - intake-esm
  - gcsfs
  #
  - pip
  - pip:
    - nbsphinx
    - jupyter_client
    - sphinx_pangeo_theme
    - sphinxcontrib-srclinks
